-- Phase 3 nutrition backfill, generated by scripts/build-backfill-sql.mjs from
-- migrations/data/nutrition_backfill.json. Deterministic and sorted by recipe id.
-- refined_carb_heavy and contains_nuts are set by refresh_recipe_derived() in 012, which also
-- needs recipe_ingredients (010) in place — that's why is_protein_smart can't be assessed until
-- after 012 runs, even though sugars_g lands here in 011.

update public.recipes set sugars_g = 4, saturates_g = 5, salt_g = 0.9, spice_level = 3, nutrition_source = 'backfill_estimate' where id = 1;
update public.recipes set sugars_g = 5, saturates_g = 2, salt_g = 1.1, spice_level = 4, nutrition_source = 'backfill_estimate' where id = 3;
update public.recipes set sugars_g = 22, saturates_g = 7, salt_g = 0.15, spice_level = 1, nutrition_source = 'backfill_estimate' where id = 4;
update public.recipes set sugars_g = 9, saturates_g = 1.5, salt_g = 1.3, spice_level = 3, nutrition_source = 'backfill_estimate' where id = 5;
update public.recipes set sugars_g = 4, saturates_g = 2, salt_g = 1, spice_level = 4, nutrition_source = 'backfill_estimate' where id = 6;
update public.recipes set sugars_g = 8, saturates_g = 3, salt_g = 1.2, spice_level = 3, nutrition_source = 'backfill_estimate' where id = 7;
update public.recipes set sugars_g = 3, saturates_g = 3, salt_g = 1.1, spice_level = 3, nutrition_source = 'backfill_estimate' where id = 8;
update public.recipes set sugars_g = 9, saturates_g = 6, salt_g = 1.6, spice_level = 4, nutrition_source = 'backfill_estimate' where id = 9;
update public.recipes set sugars_g = 32, saturates_g = 9, salt_g = 0.1, spice_level = 1, nutrition_source = 'backfill_estimate' where id = 10;
update public.recipes set sugars_g = 3, saturates_g = 1.5, salt_g = 1, spice_level = 3, nutrition_source = 'backfill_estimate' where id = 11;
update public.recipes set sugars_g = 2, saturates_g = 1, salt_g = 1, spice_level = 3, nutrition_source = 'backfill_estimate' where id = 12;
update public.recipes set sugars_g = 1.5, saturates_g = 1.5, salt_g = 1, spice_level = 3, nutrition_source = 'backfill_estimate' where id = 13;
update public.recipes set sugars_g = 6, saturates_g = 4, salt_g = 1.1, spice_level = 5, nutrition_source = 'backfill_estimate' where id = 14;
update public.recipes set sugars_g = 3, saturates_g = 3, salt_g = 0.9, spice_level = 2, nutrition_source = 'backfill_estimate' where id = 15;
update public.recipes set sugars_g = 8, saturates_g = 4, salt_g = 1.4, spice_level = 3, nutrition_source = 'backfill_estimate' where id = 16;
update public.recipes set sugars_g = 6, saturates_g = 5, salt_g = 1.2, spice_level = 2, nutrition_source = 'backfill_estimate' where id = 17;
update public.recipes set sugars_g = 2, saturates_g = 1.5, salt_g = 1, spice_level = 3, nutrition_source = 'backfill_estimate' where id = 18;
update public.recipes set sugars_g = 3, saturates_g = 1.5, salt_g = 1, spice_level = 4, nutrition_source = 'backfill_estimate' where id = 19;
update public.recipes set sugars_g = 3, saturates_g = 2, salt_g = 1.3, spice_level = 4, nutrition_source = 'backfill_estimate' where id = 20;
update public.recipes set sugars_g = 24, saturates_g = 6, salt_g = 0.1, spice_level = 1, nutrition_source = 'backfill_estimate' where id = 21;
update public.recipes set sugars_g = 5, saturates_g = 6, salt_g = 1.3, spice_level = 4, nutrition_source = 'backfill_estimate' where id = 22;
update public.recipes set sugars_g = 5, saturates_g = 6, salt_g = 1.3, spice_level = 4, nutrition_source = 'backfill_estimate' where id = 23;
update public.recipes set sugars_g = 28, saturates_g = 4, salt_g = 0.2, spice_level = 1, nutrition_source = 'backfill_estimate' where id = 24;
update public.recipes set sugars_g = 6, saturates_g = 1.5, salt_g = 1.8, spice_level = 5, nutrition_source = 'backfill_estimate' where id = 25;
update public.recipes set sugars_g = 9, saturates_g = 1.5, salt_g = 1.4, spice_level = 3, nutrition_source = 'backfill_estimate' where id = 26;
update public.recipes set sugars_g = 26, saturates_g = 5, salt_g = 0.1, spice_level = 1, nutrition_source = 'backfill_estimate' where id = 27;
update public.recipes set sugars_g = 3, saturates_g = 2, salt_g = 1.3, spice_level = 4, nutrition_source = 'backfill_estimate' where id = 28;
update public.recipes set sugars_g = 7, saturates_g = 1.5, salt_g = 1.7, spice_level = 4, nutrition_source = 'backfill_estimate' where id = 29;
update public.recipes set sugars_g = 5, saturates_g = 3, salt_g = 1.1, spice_level = 5, nutrition_source = 'backfill_estimate' where id = 30;
